theme: jekyll-theme-hacker
title: Hexq
description: Свалка мыслей
logo: logo.svg
owner:
   name: Vladimir S Kravchenko
   email: kvover@gmail.com
   github: HexQuant
markdown: kramdown
kramdown:
   math_engine: mathjax
github:
  is_project_page: false
